sudo: required
dist: trusty
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6

language: cpp

script:
  - cd $TRAVIS_BUILD_DIR
  - clang++ -std=c++11 -O0 -msse4.2 -o $TRAVIS_BUILD_DIR/xo-math/build/a.out $TRAVIS_BUILD_DIR/xo-math/Main.cpp
  - g++ -std=c++11 -O0 -msse4.2 -o $TRAVIS_BUILD_DIR/xo-math/build/a.out $TRAVIS_BUILD_DIR/xo-math/Main.cpp