sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

script:
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER && make
  - ./a.out

after_success:
  - cat $DEPLOY_KEY > .travis/deploy_key.pem
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - cd xo-math
  - node build_dist.js
  - cd ../
  - git add ./xo-math.h
  - git commit -m 'generating xo-math from sources [ci skip]'
  - git push -f -q https://xoorath:$GITHUB_API_KEY@github.com/xoorath/xo-math &2>/dev/null