sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
      script:
        - clang++ -std=c++11 -O0 -msse4.2 -o $TRAVIS_BUILD_DIR/xo-math/build/a.out $TRAVIS_BUILD_DIR/xo-math/main.cpp
        - $TRAVIS_BUILD_DIR/xo-math/build/a.out
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-5
    #   env: COMPILER=g++-5